plugins {
    id 'net.fabricmc.fabric-loom' version '1.8-SNAPSHOT'
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = "hacked-client"
}

repositories {
    maven { url = "https://fabricmc.net" } // 帶有 maven. 前綴的正式庫路徑
    maven { url = "https://minecraft.net" } 
    mavenCentral()
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    
    // 26.1 官方去混淆映射基礎（強制保留，自動工具才能運作）
    mappings loom.officialMojangMappings()
    
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
}

processResources {
    inputs.property "version", project.version
    filteringCharset "UTF-8"

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 25
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

jar {
    from("LICENSE") {}
}
